### ISSUE TITLE
Why do i 59.2k points for issues?

### ISSUE THREAD

**Issue by nainardev** [ryo-ma/github-profile-trophy#13]
https://github-profile-trophy.vercel.app/?username=nainardev

**Comment by spenserblack** [comment]
@nainardev Looking at your profile, I see you have a lot of issues opened in nainardev//tamil-dubbed. It says you opened 9,901 issues in that repo in one day :astonished: 
I'm guessing you used a script that created a lot of issues at once. I then looked at the [API response for that repo](https://api.github.com/repos/nainardev/tamil-dubbed) (this project uses GraphQL, but the results should be similar). There are 58955 issues according to the API response. Again, I'm only guessing, but I think that you created these issues with a script, because that is an unusually large number of issues. Please correct me if my guesses about how these issues were created are wrong :slightly_smiling_face: 

If GitHub attributes all these issues to you, you will have a trophy for all of these issues.

**Comment by nainardev** [comment]
Oh ! i forgot! I had set up a cron job to create issues. Got Suspended within 2 days.. Had to explain to GitHub that i'm not a bot.

**Comment by nainardev** [comment]
That cron job supported 50,000 jobs per day! But GitHub didn't allow that many
