### ISSUE TITLE
Created other "Joined" trophies

### ISSUE THREAD

**Issue by CodeMaster7000** [ryo-ma/github-profile-trophy#176]
I would like to know why there is only a "Joined2020 trophy". I think it would be more suitable for everyone to have a trophy with the year they joined GitHub.

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000, I don't think that would then highlight an achievement. If more were added, then even those who joined before 2010 would not have a trophy that would be significant anymore.

**Comment by CodeMaster7000** [comment]
@SmashedFrenzy16 The trophies could be of different levels - say Joined2022 could be "C" but Joined2010 or before could be "SSS". It would not be a bad idea.

**Comment by SmashedFrenzy16** [comment]
@CodeMaster7000, I think before 2010 is significant because you would have been on GitHub for a long time and nearly or maybe even an OG user. 2020 was COVID, which is why the trophy was made, I am presuming. But what you are saying is not a bad idea - it is just that some years have much more significance (on GitHub) than others.

**Comment by SmashedFrenzy16** [comment]
And also, these year badges are secrets, and do not follow the usual system, and are hard to obtain (like said in the README).
