### ISSUE TITLE
AllSuperRankTrophy seems to be unreachable

### ISSUE THREAD

**Issue by ppfeister** [ryo-ma/github-profile-trophy#271]
Noticed something earlier. Not sure if you guys have considered it.

AllSuperRank was previously only ever attainable by those who were registered in 2008, as there was no other way to earn AncientAccount and OGAccount. With the addition of Joined2020, this trophy seems to not be attainable by any users whatsoever.

Those who would have originally earned it by being 2008 account holders would have also theoretically lost the trophy, since they were registered _before_ 2020 and not _in_ 2020. Those registered _in_ 2020 are not eligible for the same reason -- having registered after both 2008 and 2010.

Is there something I'm missing?

**Comment by Ghostcoder59** [comment]
You've identified a valid concern regarding the AllSuperRank trophy's eligibility criteria.  
So, the following is the current criteria:
AncientAccount: Awarded to users registered in 2008.
OGAccount: Awarded to users registered in 2010.
Joined2020: Awarded to users registered in 2020.
AND THE MAIN ISSUE HERE IS THAT:
Users who registered in-
2008 can only qualify for AncientAccount.
2010 can only qualify for OGAccount.
 2020 can only qualify for Joined2020.
Since it's impossible for a single user to meet all 3 criteria (bcoz one cannot be registered in 2008, 2010, and 2020 simultaneously), no user can currently attain the AllSuperRank trophy.
