### ISSUE TITLE
Feature Request: Filter Rank

### ISSUE THREAD

**Issue by EdamAme-x** [ryo-ma/github-profile-trophy#272]
Filter, Rank, Name, etc...

**Comment by a2ys** [comment]
This issue might get marked as stale by the GitHub bot. Can you add a better description of what you want?

**Comment by EdamAme-x** [comment]
Thanks @a2ys 
I would like the ability to select/filter which trophies to display by query.

**Comment by a2ys** [comment]
@EdamAme-x 

From what you've said, I think you want something like displaying specific trophies. This feature is already there. You can refer to the very [beginning of the README](https://github.com/ryo-ma/github-profile-trophy?tab=readme-ov-file#filter-by-titles). This is what it says.

```
https://github-profile-trophy.vercel.app/?username=ryo-ma&title=Followers
```
When you give this query, the card with only the Followers title will be displayed. If you want more cards, you can call this query.

```
https://github-profile-trophy.vercel.app/?username=ryo-ma&title=Stars,Followers
```

This will display the cards with only the title Stars and Followers.

If you want more help, follow-up on this discussion!

**Comment by EdamAme-x** [comment]
thanks @a2ys . I'll use this.

**Comment by a2ys** [comment]
@EdamAme-x 

Also, based on your query, I have added a new query where you can exclude specific trophies as well (PR #276) ! This would be helpful if you want to not display just one or two trophies, so instead of having to write all the trophies, you can just write the trophies you don't want to display.

The pull request is open as of now, but if it gets merged, it might be helpful to you! You can subscribe to the PR to have a close watch.
